name: pokedex_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  equatable: ^2.0.5
  palette_generator: ^0.3.3+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  mockito: ^5.3.2
  build_runner:


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
